USE `vastra_mahal_db`;

-- Clear existing data if any
DELETE FROM `products`;
DELETE FROM `categories`;

-- Insert Categories
INSERT INTO `categories` (`id`, `name`, `slug`, `image`, `description`, `is_featured`, `status`) VALUES
(1, 'Girl Suits & Partywear', 'girl-suits', 'images/categories/cat-girls-suit.jpg', 'Designer Punjabi suits, trendy shararas, peplum sets, and partywear suits crafted especially for young women & girls.', 1, 'active'),
(2, 'Banarasi Silk Sarees', 'banarasi-sarees', 'images/categories/cat-banarasi.jpg', 'Authentic pure Katan silk Banarasi sarees with antique gold & silver zari work from the master weavers of Varanasi.', 1, 'active'),
(3, 'Designer Anarkali & Suits', 'designer-anarkali-suits', 'images/categories/cat-anarkali.jpg', 'Royal floor-length flared Anarkalis and designer ethnic suits with intricate thread & sequin hand embroidery.', 1, 'active'),
(4, 'Bridal & Festive Lehengas', 'bridal-lehengas', 'images/categories/cat-lehenga.jpg', 'Opulent velvet and silk bridal lehengas featuring traditional zardozi, dabka, and gotta patti craftsmanship.', 1, 'active'),
(5, 'Kanjivaram Silk Sarees', 'kanjivaram-sarees', 'images/categories/cat-kanjivaram.jpg', 'Timeless South Indian pure mulberry silk Kanjivaram sarees adorned with sacred temple borders and rich pallus.', 1, 'active'),
(6, 'Designer Kurtis & Tunics', 'designer-kurtis', 'images/categories/cat-kurti.jpg', 'Breezy Chanderi, Georgette, and pure silk designer kurtis and co-ord sets for elegant daily and festive wear.', 1, 'active');

-- Insert Products
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sku`, `price`, `sale_price`, `fabric`, `color`, `work_type`, `short_desc`, `description`, `main_image`, `is_featured`, `is_new_arrival`, `in_stock`, `status`) VALUES
(1, 1, 'Gulabi Noor - Girls Mirror Work Sharara Suit', 'gulabi-noor-girls-sharara-suit', 'VM-GIRL-001', 3999.00, 2799.00, 'Georgette & Pure Organza', 'Pastel Powder Pink', 'Real Mirror & Zari Hand Embroidery', 'Stunning pastel pink sharara suit for girls featuring delicate mirror work and flared tiered pants.', 'Embrace festive elegance with the Gulabi Noor Sharara Suit. Tailored for young girls and festive occasions, this 3-piece designer set includes a finely crafted short kurti with authentic mirror work along the neckline, paired with a multi-tiered pleated sharara and a lightweight organza dupatta with scalloped borders. Perfect for weddings, sangeet, and festive celebrations.', 'images/products/prod-girls-pastel-sharara.jpg', 1, 1, 1, 'active'),

(2, 1, 'Kesariya Phulkari - Girls Punjabi Salwar Suit', 'kesariya-phulkari-girls-punjabi-suit', 'VM-GIRL-002', 3499.00, 2499.00, 'Chanderi Silk & Georgette', 'Mustard Yellow & Rani Pink', 'Gota Patti & Resham Embroidery', 'Vibrant mustard yellow Punjabi suit with heavy contrast phulkari-style embroidered dupatta.', 'A radiant festive ensemble celebrating traditional Punjabi craftsmanship. Features a rich mustard yellow Chanderi kurti with golden thread accents, paired with comfortable churidar/patiala pants and an eye-catching magenta phulkari dupatta. A showstopper choice for Haldi, Diwali, and festive gatherings.', 'images/products/prod-girls-punjabi-suit.jpg', 1, 1, 1, 'active'),

(3, 1, 'Lavender Bloom - Girls Tiered Peplum Sharara Set', 'lavender-bloom-girls-peplum-sharara', 'VM-GIRL-003', 4499.00, 3199.00, 'Silk Georgette', 'Pastel Lavender', 'Fine Sequin & Pearl Handwork', 'Charming lavender peplum kurti with multi-tiered ruffled sharara and embellished tassels.', 'Designed for contemporary grace, this lavender peplum sharara set combines modern silhouette with royal Indian hand embroidery. Crafted in soft breathable silk georgette with delicate pearl and sequin embroidery along the yoke and hems. Comes with matching ruffled sharara and dupatta.', 'images/products/prod-girls-lavender-sharara.jpg', 1, 1, 1, 'active'),

(4, 2, 'Royal Crimson Katan Banarasi Silk Saree', 'royal-crimson-katan-banarasi-saree', 'VM-SAREE-001', 18999.00, 14499.00, 'Pure Katan Silk', 'Crimson Red & Antique Gold', 'Handwoven Kadwa Zari Weave', 'Authentic handwoven Varanasi pure silk saree featuring floral jangla zari work and rich brocade pallu.', 'Woven by master artisans in Varanasi, this crimson red Banarasi saree is a timeless heirloom piece. Features intricate Kadwa floral motifs in pure tested gold zari across the body, complemented by a grand floral meenakari border and a lavish heavy pallu. Comes with an unstitched matching blouse piece with border.', 'images/products/prod-banarasi-crimson.jpg', 1, 1, 1, 'active'),

(5, 2, 'Meghdoot Hand-Painted Pure Organza Silk Saree', 'meghdoot-hand-painted-organza-saree', 'VM-SAREE-002', 12499.00, 8999.00, 'Pure Organza Silk', 'Powder Sky Blue & Floral Pastel', 'Hand-Painted Floral with Pearl Scalloped Border', 'Ethereal powder blue organza saree adorned with artistic botanical florals and pearl beaded borders.', 'A breathtaking blend of modern couture and royal grace. This pure organza silk saree features pastel floral motifs individually hand-painted by artists, framed with delicate pearl beads and hand-scalloped embroidery. Super lightweight, translucent drape that exudes effortless royal charm.', 'images/products/prod-floral-organza-saree.jpg', 1, 1, 1, 'active'),

(6, 3, 'Nilambari - Royal Navy Blue Designer Anarkali Suit', 'nilambari-royal-navy-anarkali-suit', 'VM-SUIT-001', 11999.00, 8499.00, 'Pure Silk Georgette', 'Royal Navy Blue & Gold', 'Zardozi & Antique Tilla Embroidery', 'Majestic 48-kali floor length royal blue Anarkali gown with sheer embroidered dupatta.', 'Channel royal majesty in Nilambari. This floor-sweeping Anarkali is cut with an expansive flared hemline, richly adorned with antique gold tilla and zardozi embroidery on the bodice, full sleeves, and ghera. Paired with a delicate navy organza dupatta with gold laced border and silk pants.', 'images/products/prod-navy-anarkali.jpg', 1, 1, 1, 'active'),

(7, 4, 'Shehnai - Royal Heritage Velvet Bridal Lehenga', 'shehnai-royal-velvet-bridal-lehenga', 'VM-LEH-001', 48999.00, 39999.00, 'Micro Velvet & Raw Silk', 'Deep Regal Maroon', 'Heavy Zardozi, Dabka & Stone Work', 'Masterpiece royal bridal lehenga in rich maroon velvet with opulent gold zardozi craftsmanship.', 'Every bride deserves royal magnificence. The Shehnai Bridal Lehenga is tailored in plush deep maroon velvet, hand-embroidered with thousands of gold dabka, zardozi, and micro-crystals forming Mughal floral jaals and heritage arches. Features a double dupatta concept with velvet shawl and lightweight bridal veil.', 'images/products/prod-bridal-maroon-lehenga.jpg', 1, 1, 1, 'active'),

(8, 5, 'Mayuri - Rani Pink Temple Zari Kanjivaram Silk Saree', 'mayuri-rani-pink-kanjivaram-saree', 'VM-SAREE-003', 24999.00, 19499.00, 'Pure Kanchipuram Mulberry Silk', 'Rani Magenta Pink & Temple Gold', 'Pure 2-Ply Gold Zari Temple Border', 'Traditional heirloom Kanjivaram silk saree with authentic Korvai temple border and peacock motifs.', 'Handcrafted in Tamil Nadu, this authentic Kanjivaram saree displays the renowned Korvai weaving technique. The brilliant rani magenta body is adorned with miniature rudraksha and floral buttas, meeting an imposing gold zari temple border with mayil (peacock) motifs and a dense brocade pallu.', 'images/products/prod-kanjivaram-pink-gold.jpg', 1, 1, 1, 'active'),

(9, 3, 'Kashmir Mehfil - Wine Velvet Straight Salwar Suit', 'kashmir-mehfil-wine-velvet-suit', 'VM-SUIT-002', 8999.00, 6499.00, 'Premium Silk Velvet', 'Wine Burgundy & Antique Gold', 'Kashmiri Tilla Handwork', 'Rich wine burgundy velvet straight-cut salwar suit with matching embroidered velvet shawl.', 'Ideal for winter weddings and evening soirées, Kashmir Mehfil is crafted from lush silk velvet in a deep wine hue. The neckline and sleeve cuffs are detailed with delicate Kashmiri tilla handwork. Includes matching tailored trousers and a lavish velvet shawl with paisley border.', 'images/products/prod-wine-velvet-suit.jpg', 1, 1, 1, 'active'),

(10, 6, 'Mint Zephyr - Chanderi Silk Embroidered Palazzo Suit', 'mint-zephyr-chanderi-palazzo-suit', 'VM-KURTI-001', 5499.00, 3899.00, 'Handwoven Chanderi Silk', 'Mint Green & Ivory', 'Chikankari Inspired Resham Embroidery', 'Graceful mint green Chanderi silk kurti paired with flared palazzo and organza dupatta.', 'A breath of fresh air in contemporary ethnic wear. Light, luminous Chanderi silk in a calming pastel mint shade, adorned with fine ivory resham embroidery along the neck and hemline. Pairs seamlessly with relaxed palazzo trousers and a sheer dupatta with corner tassels.', 'images/products/prod-mint-chanderi-suit.jpg', 1, 1, 1, 'active');
